#lang racket

;;; Even Fibonacci numbers
;;; Each new term in the Fibonacci sequence is generated by adding the previous two terms.
;;; By starting with 1 and 2, the first 10 terms will be:
;;;    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;;;
;;; By considering the terms in the Fibonacci sequence whose values do not exceed four million,
;;; find the sum of the even-valued terms.
;;;

(define (sum-even-fib n)
  (define (helper a b acc)
    (if (> b n)
        acc
        (helper b
                (+ a b)
                (if (even? b)
                    (+ acc b)
                    acc))))
  (helper 1 2 0))

(sum-even-fib 4000000)
